column_reference_file_name: "master_sheet_reference.xlsx" # change this to name of the column reference file
assessment_guide_file_name: "assessment_guide.xlsx" # change this to name of assessment guide file
compiled_master_sheet: "master_sheet.xlsx" # change this to the name of the compiled master sheet file you desire